### ISSUE TITLE
Uploading and Evaluating a DMN File (in Camunda version 7.5) fails with a correct DMN-File

### ISSUE THREAD

**Issue by avan2s** [camunda/camunda-engine-dmn#9]
Hello,
i can't evaluate an uploaded valid, DMN-File by using Camunda version 7.5.0. Currently i'm restricted to this version. For more information see [this post](https://forum.camunda.org/t/evaluation-of-an-uploaded-dmn-file-fails-dmn-01002-unable-to-evaluate-expression-for-language-juel/2823) Maybe you know, what i'am doing wrong?
I would be glad for a solution.
Thanks a lot for your help!

**Comment by saig0** [comment]
Hi @avan2s ,

I will close this issue here. If your problem is not fixed then please open an issue on our [Jira](https://app.camunda.com/jira/secure/Dashboard.jspa) or discuss it at the forum.

Best regards,
Philipp
